src/Entity/NutritionalProgram.php
<?php

namespace App\Entity;

use App\Repository\ProgrammeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=NutritionalProgrammeRepository::class)
 * @Vich\Uploadable
 */
class NutritionalProgram
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="this field is required ")
     */
    private $type;


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="this field is required ")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="this field is required ")
     */
    private $breackfast;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="this field is required ")
     */
    private $lunch;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="this field is required ")
     */
    private $dinner;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="nutritionalProgram", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="nuProgram")
     */
    private $comments;


    public function __construct()
    {
        $this->updatedAt = new \DateTime();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBreackfast(): ?string
    {
        return $this->breackfast;
    }

    public function setBreackfast(string $breackfast): self
    {
        $this->breackfast = $breackfast;

        return $this;
    }

    public function getLunch(): ?string
    {
        return $this->lunch;
    }

    public function setLunch(string $lunch): self
    {
        $this->lunch = $lunch;

        return $this;
    }

    public function getDinner(): ?string
    {
        return $this->dinner;
    }

    public function setDinner(string $dinner): self
    {
        $this->dinner = $dinner;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function __toString(){
        // to show the name of the Category in the select
        return $this->name;
        // to show the id of the Category in the select
        // return $this->id;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setNuProgram($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getNuProgram() === $this) {
                $comment->setNuProgram(null);
            }
        }

        return $this;
    }

//    public function getNutritionist(): ?User
//    {
//        return $this->nutritionist;
//    }
//
//    public function setNutritionist(?User $nutritionist): self
//    {
//        $this->nutritionist = $nutritionist;
//
//        return $this;
//    }

}

src/Entity/Programme.php
<?php

namespace App\Entity;

use App\Repository\ProgrammeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProgrammeRepository::class)
 */
class Programme
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/NutritionalProgramType.php
<?php

namespace App\Form;

use App\Entity\NutritionalProgram;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class NutritionalProgramType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('type')
            ->add('imageFile',VichImageType::class, [
                'required' => false,
                'allow_delete' => true,
                'delete_label' => '...',
                'download_label' => '...',
                'download_uri' => true,
                'image_uri' => true,
                'asset_helper' => true,
            ])

            ->add('description',TextType::class)
            ->add('breackfast')
            ->add('lunch')
            ->add('dinner')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => NutritionalProgram::class,
        ]);
    }
}

templates/nutritional_program/TypeB.html.twig
{% extends 'baseFrontend.html.twig' %}
{% block title %}Programme Alimentaire{% endblock %}

{% block body %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for p in programme %}

    <div class="col">
        <div class="card h-100">
            <img
                    src="{{ asset('upload/images/' ~ p.image) }}"
                    class="card-img-top"
                    alt="..."
            />
            <div class="card-body">
                <h5 class="card-title">{{ p.name }}</h5>
                <p class="card-text">
                    {{ p.description }}
                </p>
            </div>
            <div class="card-footer">
                <a href="{{ path('show_id',  {'id': p.id}) }}" class="btn btn-primary">read more</a>
                <a href="{{ path("listp",{'id': p.id }) }}" class="btn btn-primary">download</a>
            </div>
        </div>
    </div>
        <!--a href="{#  { path('make',{'id': p.id }) }#}" class="btn btn-primary">Make comment</a!-->
    {% endfor %}
    </div>
    <div class="navigation">
        {{ knp_pagination_render(programme) }}
    </div>


{% endblock %}

templates/nutritional_program/_delete_form.html.twig
<form method="post" action="{{ path('programme_delete', {'id': programme.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ programme.id) }}">
    <button class="btn">Delete</button>
</form>

templates/nutritional_program/edit.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Edit Programme{% endblock %}

{% block body %}
    <h1>Edit Programme</h1>

    {{ include('programme/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('programme_index') }}">back to list</a>

    {{ include('programme/_delete_form.html.twig') }}
{% endblock %}

templates/nutritional_program/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Programme index{% endblock %}

{% block body %}
    <h1>Programme index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Type</th>
                <th>Image</th>
                <th>Description</th>
                <th>Break_fast</th>
                <th>Dinner</th>
                <th>Lunch</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for p in programme %}
            <tr>
                <td>{{ p.id }}</td>
                <td>{{ p.name }}</td>
                <td>{{ p.type }}</td>
                <td>{{ p.imageFile }}</td>
                <td>{{ p.description }}</td>
                <td>{{ p.breackfast }}</td>
                <td>{{ p.lunch }}</td>
                <td>{{ p.dinner }}</td>
                <td>
                    <a href="{{ path('programme_show', {'id': p.id}) }}">show</a>
                    <a href="{{ path('programme_edit', {'id': p.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('programme_new') }}">Create new</a>
{% endblock %}

templates/nutritional_program/listp.html.twig
{% block body %}
    {% if programme %}
    <h1>your programme</h1>
    <table class="table">
        <thead>
        <tr>

            <th>Name</th>
            <th>Type</th>
            <th>Description</th>
            <th>Break_fast</th>
            <th>Dinner</th>
            <th>Lunch</th>
        </tr>
        </thead>
        <tbody>


            <tr>
                <td>{{ programme.name }}</td>
                <td>{{ programme.type }}</td>
                <td>{{ programme.description }}</td>
                <td>{{ programme.breackfast }}</td>
                <td>{{ programme.lunch }}</td>
                <td>{{ programme.dinner }}</td>
            </tr>

    {% else%}
        <p>not found</p>
    {% endif %}
        </tbody>
    </table>

{% endblock %}

templates/nutritional_program/make.html.twig
{% extends 'baseFrontend.html.twig' %}
{% block title %}your programme{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>Comments</h3>
            </div><!-- /col-sm-12 -->
        </div><!-- /row -->
        {% for c in comments %}
            <div class="row">
                <div class="col-sm-5">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <strong>{{ c.authorName }}</strong> <span class="text-muted">commented At {{ c.createdAt | date('d/m/y') }}</span>
                        </div>
                        <div class="panel-body">
                            {{ c.content }}
                        </div><!-- /panel-body -->
                    </div><!-- /panel panel-default -->
                </div><!-- /col-sm-5 -->
            </div><!-- /row -->
        {% endfor %}
    </div>
    {% for p in programme %}
        <div class="container">
        <div class="row">
        <div class="col-xs-12 col-sm-7" id="new_status">
            <div class="navbar-nav col-xs-12" id="post_header" role="navigation">

                <form action="{{ path('make',{'id': p.id}) }}" method="post" >
                    <div class="col-xs-12" id="post_content">
                        <div class="textarea_wrap">
                            {{ form_start(commentForm) }}
                            {{ form_widget(commentForm.content,{'attr':{'placeholder':'Leave Comment','class':'form-control','rows':'5'}}) }}
                            {{ form_widget(commentForm) }}
                            <div class="col-xs-5">
                                <button class="btn btn-primary btn-block">{{ button_label|default('Post') }}</button>
                            </div>
                            {{ form_end(commentForm) }}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    {% endfor %}
    <script src="https://use.fontawesome.com/1dec14be15.js"></script>
    <script>
        // If user clicks anywhere outside of the modal, Modal will close
        var modal = document.getElementById('modal-wrapper');
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>

{% endblock %}

templates/nutritional_program/new.html.twig
{% extends 'base2.html.twig' %}

{% block title %}New Programme{% endblock %}

{% block body %}
    <h1>Create new Programme</h1>

    {{ include('programme/_form.html.twig') }}

    <a href="{{ path('programme_index') }}">back to list</a>
{% endblock %}

templates/nutritional_program/show.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Programme{% endblock %}

{% block body %}
    <h1>Programme</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ programme.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ programme.name }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ programme.type }}</td>
            </tr>
            <tr>
                <th>image</th>
                <td>{{ programme.imageFile }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ programme.description }}</td>
            </tr>
            <tr>
                <th>Break_fast</th>
                <td>{{ programme.breackfast }}</td>
            </tr>
            <tr>
                <th>Dinner</th>
                <td>{{ programme.dinner }}</td>
            </tr>
            <tr>
                <th>Lunch</th>
                <td>{{ programme.lunch }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('programme_index') }}">back to list</a>

    <a href="{{ path('programme_edit', {'id': programme.id}) }}">edit</a>

    {{ include('programme/_delete_form.html.twig') }}
{% endblock %}

templates/nutritional_program/showid.html.twig
{% extends 'baseFrontend.html.twig' %}

{% block title %}Programme{% endblock %}

{% block body %}
    <h1>Programme</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Name</th>
            <td>{{ programme.name }}</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>{{ programme.type }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ programme.description }}</td>
        </tr>
        <tr>
            <th>Break_fast</th>
            <td>{{ programme.breackfast }}</td>
        </tr>
        <tr>
            <th>Dinner</th>
            <td>{{ programme.dinner }}</td>
        </tr>
        <tr>
            <th>Lunch</th>
            <td>{{ programme.lunch }}</td>
        </tr>
        </tbody>
    </table>
    <p>to make a specialized program for you you can consult a nutritionist</p>
    <a href="{{ path("showf") }}" class="btn btn-primary">consult</a>
{% for comment in comments %}
    <div class="row">
        <div class="col-sm-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>{{ comment.patient.nom }}</strong> <span class="text-muted">commented At {{ comment.createdAt | date('d/m/y') }}</span>
                </div>
                <div class="panel-body">
                    {{ comment.content }}
                </div><!-- /panel-body -->
            </div><!-- /panel panel-default -->
        </div><!-- /col-sm-5 -->
    </div><!-- /row -->

{% endfor %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-7" id="new_status">
            <form action="{{ path('show_id',{'id': programme.id}) }}" method="post" >
                <div class="col-xs-12" id="post_content">
                    <div class="textarea_wrap">
                        {{ form_start(commentForm) }}
                        {{ form_widget(commentForm.content,{'attr':{'placeholder':'Leave Comment','class':'form-control','rows':'5'}}) }}
                        {{ form_widget(commentForm) }}
                        <div class="col-xs-5">
                            <button class="btn btn-primary btn-block">{{ button_label|default('Post') }}</button>
                        </div>
                        {{ form_end(commentForm) }}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

templates/nutritional_program/typeA.html.twig
{% extends 'baseFrontend.html.twig' %}
{% block title %}Programme Alimentaire{% endblock %}

{% block body %}

    <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for p in programme %}
    <div class="col">
        <div class="card h-100">


            <img
                    src="{{ asset('upload/images/' ~ p.image) }}"
                    class="card-img-top"
                    alt="..."

            />
            <div class="card-body">
                <h5 class="card-title">{{ p.name }}</h5>
                <p class="card-text">
                    {{ p.description }}
                </p>
                <div class="card-footer">
                    <a href="{{ path('show_id',  {'id': p.id}) }}" class="btn btn-primary">Read more</a>
                    <a href="{{ path("listp",{'id': p.id }) }}" class="btn btn-primary">download</a>
                </div>
            </div>

    </div>

        {% endfor %}
    </div>
    <div class="navigation">
        {{ knp_pagination_render(programme) }}
    </div>


{% endblock %}

templates/nutritional_program/typeC.html.twig
{% extends 'baseFrontend.html.twig' %}
{% block title %}Programme Alimentaire{% endblock %}

{% block body %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for p in programme %}
            <div class="col">
                <div class="card h-100">
                    <img
                            src="{{ asset('upload/images/' ~ p.image) }}"
                            class="card-img-top"
                            alt="..."
                    />
                    <div class="card-body">
                        <h5 class="card-title">{{ p.name }}</h5>
                        <p class="card-text">
                            {{ p.description }}
                        </p>
                    </div>
                    <div class="card-footer">
                        <a href="{{ path('show_id',  {'id': p.id}) }}" class="btn btn-primary">read more</a>
                        <a href="{{ path("listp",{'id': p.id }) }}" class="btn btn-primary">download</a>
                    </div>

                </div>
                </div>


        {% endfor %}
    </div>
    <div class="navigation">
        {{ knp_pagination_render(programme) }}
    </div>

{% endblock %}